<?php
namespace frontend\widgets;
use backend\models\GoodsCategory;
use yii\base\Widget;

class CategoryWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        //加测redis是否有商品分类缓存
        //$redis=new \Redis();
        //$redis->connect('127.0.0.1');
        //$category_html=$redis->get('category_html');
        //if($category_html==null){
            //读取所有一级分类
            $categories=GoodsCategory::findAll(['parent_id'=>0]);
            $category_html=$this->renderFile('@app/widgets/view/category.php',['categories'=>$categories]);
            //$redis->set('category_html',$category_html);
        //}

        return $category_html;
    }
}